name: CI Pipeline para App Matemáticas

on: [push]  

jobs:
  build-and-test:
    runs-on: windows-latest  # Necesario para WPF/XAML
    steps:
      - uses: actions/checkout@v2  # Descarga tu código
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Usa tu versión de .NET

      - name: Build
        run: dotnet build --configuration Release  # Compila el proyecto

      - name: Run Tests
        run: dotnet test  # Ejecuta pruebas unitarias
