name: CI - MAUI App (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar .NET 8 y workloads de MAUI
      run: |
        dotnet workload install maui
        dotnet workload install maui-windows

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar para Windows
      run: dotnet build Act3.csproj -f net8.0-windows10.0.19041.0 --configuration Release --no-restore
